# version: "3.9"

services:
  db:
    image: timescale/timescaledb:latest-pg15
    container_name: mobilidade_db
    environment:
      POSTGRES_DB: monitoramento
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d monitoramento" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mobilidade_net

  collector:
    build: ./collector
    container_name: mobilidade_collector
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mobilidade_net

  api:
    build: ./api
    container_name: mobilidade_api
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./api/features.py:/app/features.py:ro
      - ./api/predict.py:/app/predict.py:ro
      - ./ml/model_15m.pkl:/app/model_15m.pkl:ro
      - ./ml/model_30m.pkl:/app/model_30m.pkl:ro
      - ./ml/model_60m.pkl:/app/model_60m.pkl:ro
      - ./ml/model.pkl:/app/model.pkl:ro # Compatibilidade
      - ./ml:/app/ml
    networks:
      - mobilidade_net

  dashboard:
    build: ./dashboard
    container_name: mobilidade_dashboard
    env_file: .env
    depends_on:
      api:
        condition: service_started
    ports:
      - "8501:8501"
    restart: unless-stopped
    networks:
      - mobilidade_net

networks:
  mobilidade_net:
    driver: bridge

volumes:
  pgdata:
